name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Compilar APK con Buildozer
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-11-jdk python3-pip python3-setuptools \
            python3 python3-dev build-essential ccache libncurses5 \
            libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
            libpng-dev libfreetype6-dev liblcms2-dev libblas-dev \
            liblapack-dev libatlas-base-dev libgstreamer1.0 libgstreamer1.0-dev \
            libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev xclip xsel \
            libgstreamer-plugins-base1.0-dev libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Instalar Buildozer y dependencias Python
        run: |
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Inicializar Buildozer
        run: |
          buildozer android debug

      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
